/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cod;

import java.awt.Color;

/**
 *
 * @author PESSOAL
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    ArvBin arv;
    No[] aux = new No[7];
    javax.swing.JLabel[] label = new javax.swing.JLabel[13];
    
    public TelaPrincipal() {
        arv = new ArvBin();
        initComponents();
        label[0] = raiz;
        label[1] = no1;
        label[2] = no2;
        label[3] = no3;
        label[4] = no4;
        label[5] = no5;
        label[6] = no6;
        label[7] = seta0;
        label[8] = seta1;
        label[9] = seta2;
        label[10] = seta3;
        label[11] = seta4;
        label[12] = seta5;
        
        Invisible();    

    }
    
    public void setVisibleRaiz(){
        No aux = arv.getRaiz();
        if(aux != null){
            label[0].setVisible(true);
            int n = aux.getConteudo();
            label[0].setText(Integer.toString(n));
        }
    }
    
    public void setVisible(){
        aux[0] = arv.getRaiz();
        if(aux[0] != null){
            label[0].setVisible(true);
            int n0 = aux[0].getConteudo();
            label[0].setText(Integer.toString(n0));
        }
        aux[1] = aux[0].getEsq();
        if(aux[1] != null){
            int n1 = aux[1].getConteudo();
            label[1].setText(Integer.toString(n1));
            label[1].setVisible(true);
            label[7].setVisible(true);
            
            aux[3] = aux[1].getEsq();
            if(aux[3] != null){
                int n3 = aux[3].getConteudo();
                label[3].setText(Integer.toString(n3));
                label[3].setVisible(true);
                label[9].setVisible(true);
            }
            aux[4] = aux[1].getDir();
            if(aux[4] != null){
                int n4 = aux[4].getConteudo();
                label[4].setText(Integer.toString(n4));
                label[4].setVisible(true);
                label[10].setVisible(true);
            }
            
        }
        
        aux[2] = aux[0].getDir();
        if(aux[2] != null){
            int n2 = aux[2].getConteudo();
            label[2].setText(Integer.toString(n2));
            label[2].setVisible(true);
            label[8].setVisible(true);
        
            aux[5] = aux[2].getEsq();
            if(aux[5] != null){
                int n5 = aux[5].getConteudo();
                label[5].setText(Integer.toString(n5));
                label[5].setVisible(true);
                label[11].setVisible(true);
            }
            
            aux[6] = aux[2].getDir();
            if(aux[6] != null){
                int n6 = aux[6].getConteudo();
                label[6].setText(Integer.toString(n6));
                label[6].setVisible(true);
                label[12].setVisible(true);
            }
        }
        
    }
        
    
   
    public void Invisible(){
        for(int i = 0; i < 13;i++){
            label[i].setVisible(false);
        }
        
    }
    
    
    private boolean verificarPai(int valor){
        boolean achou = false;
        for(int i = 0; i < 7; i++) {
            if(label[i].getText() != ""){
                if(Integer.parseInt(label[i].getText()) == valor)
                    achou = true;
            }
        }
        if(!achou)
            System.out.println("O Valor pai não consta na arvore");
        
        return achou;
    }
    
    private boolean verificarFilho(int valor){
        boolean achou = false;
         for(int i = 0; i < 7; i++) {
            if(label[i].getText() != ""){
                if(Integer.parseInt(label[i].getText()) == valor){
                    System.out.println("Valor filho já consta na arvore");
                    achou = true;
                }
            }
        }
         return achou;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bBusca = new javax.swing.JButton();
        bInOrdem = new javax.swing.JButton();
        bPreOrdem = new javax.swing.JButton();
        bPosOrdem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vPai = new javax.swing.JTextField();
        vFilho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIn = new javax.swing.JLabel();
        txtPre = new javax.swing.JLabel();
        txtPos = new javax.swing.JLabel();
        bInsereDir = new javax.swing.JButton();
        no1 = new javax.swing.JLabel();
        no2 = new javax.swing.JLabel();
        raiz = new javax.swing.JLabel();
        no3 = new javax.swing.JLabel();
        no4 = new javax.swing.JLabel();
        no5 = new javax.swing.JLabel();
        no6 = new javax.swing.JLabel();
        bInsereEsq = new javax.swing.JButton();
        bInsereRaiz = new javax.swing.JButton();
        vRaiz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vBusca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        seta1 = new javax.swing.JLabel();
        seta0 = new javax.swing.JLabel();
        seta2 = new javax.swing.JLabel();
        seta3 = new javax.swing.JLabel();
        seta4 = new javax.swing.JLabel();
        seta5 = new javax.swing.JLabel();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ÁRVORE BINÁRIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 0, -1, -1));

        bBusca.setBackground(new java.awt.Color(153, 204, 255));
        bBusca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bBusca.setText("Buscar");
        bBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(bBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, -1, -1));

        bInOrdem.setBackground(new java.awt.Color(153, 204, 255));
        bInOrdem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bInOrdem.setText("IN-ORDEM");
        bInOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInOrdemActionPerformed(evt);
            }
        });
        jPanel1.add(bInOrdem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 105, -1));

        bPreOrdem.setBackground(new java.awt.Color(153, 204, 255));
        bPreOrdem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bPreOrdem.setText("PRÉ-ORDEM");
        bPreOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPreOrdemActionPerformed(evt);
            }
        });
        jPanel1.add(bPreOrdem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 313, -1, -1));

        bPosOrdem.setBackground(new java.awt.Color(153, 204, 255));
        bPosOrdem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bPosOrdem.setText("PÓS-ORDEM");
        bPosOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPosOrdemActionPerformed(evt);
            }
        });
        jPanel1.add(bPosOrdem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 336, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 151, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 151, -1, -1));

        vPai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vPaiActionPerformed(evt);
            }
        });
        jPanel1.add(vPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 154, 37, 28));

        vFilho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vFilhoActionPerformed(evt);
            }
        });
        jPanel1.add(vFilho, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 154, 37, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Pai:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 158, -1, -1));

        txtIn.setText("-");
        jPanel1.add(txtIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 367, 244, 21));

        txtPre.setText("-");
        jPanel1.add(txtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 315, 244, 21));

        txtPos.setText("-");
        jPanel1.add(txtPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 336, 244, 21));

        bInsereDir.setBackground(new java.awt.Color(102, 204, 255));
        bInsereDir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bInsereDir.setText("Inserir a Direita");
        bInsereDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsereDirActionPerformed(evt);
            }
        });
        jPanel1.add(bInsereDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 188, 135, -1));

        no1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 50, 25));

        no2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(no2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 50, 25));

        raiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        raiz.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 50, 25));

        no3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(no3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 50, 25));

        no4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(no4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 50, 25));

        no5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(no5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 50, 25));

        no6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(no6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 50, 25));

        bInsereEsq.setBackground(new java.awt.Color(102, 204, 255));
        bInsereEsq.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bInsereEsq.setText("Inserir a Esquerda");
        bInsereEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsereEsqActionPerformed(evt);
            }
        });
        jPanel1.add(bInsereEsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, -1, -1));

        bInsereRaiz.setBackground(new java.awt.Color(102, 204, 255));
        bInsereRaiz.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bInsereRaiz.setText("Inserir na Raiz");
        bInsereRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsereRaizActionPerformed(evt);
            }
        });
        jPanel1.add(bInsereRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 139, 28));

        vRaiz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vRaizActionPerformed(evt);
            }
        });
        jPanel1.add(vRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 34, 37, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, 29));

        vBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(vBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 249, 37, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Valor:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 253, -1, -1));

        seta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cod/40.png"))); // NOI18N
        jPanel1.add(seta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 42, -1));

        seta0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cod/60.png"))); // NOI18N
        jPanel1.add(seta0, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        seta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cod/60.png"))); // NOI18N
        jPanel1.add(seta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        seta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cod/40.png"))); // NOI18N
        jPanel1.add(seta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        seta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cod/60.png"))); // NOI18N
        jPanel1.add(seta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        seta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cod/40.png"))); // NOI18N
        jPanel1.add(seta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atualiza(){
        setVisibleRaiz();
        setVisible();
        
        for(int i = 0; i < 7; i++){
            if(label[i].getText() != null)
                
                label[i].setForeground(Color.black);
        }
    }
    
    private void bInsereRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsereRaizActionPerformed
        int valor;
        if(vRaiz.getText() == null){
            System.out.println("Nenhum valor digitado no campo");
        }
        else{
            if(vRaiz.getText() != null){
                valor = Integer.parseInt(vRaiz.getText());
                arv.insereRaiz(valor);
            }
        }
        atualiza();
    }//GEN-LAST:event_bInsereRaizActionPerformed

    private void bInsereEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsereEsqActionPerformed

        int vfilho = Integer.parseInt(vFilho.getText());
        int vpai = Integer.parseInt(vPai.getText());
        boolean filho, pai;
        
        filho = verificarFilho(vfilho);
        pai = verificarPai(vpai);
        
        if(filho != true && pai != false)
            arv.insereEsq(vpai, vfilho);
        atualiza();
    }//GEN-LAST:event_bInsereEsqActionPerformed

    private void bInsereDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsereDirActionPerformed
        int vfilho = Integer.parseInt(vFilho.getText());
        int vpai = Integer.parseInt(vPai.getText());
        boolean filho, pai;
        
        filho = verificarFilho(vfilho);
        pai = verificarPai(vpai);
        
       if(filho != true && pai != false)
            arv.insereDir(vpai, vfilho);
        
        atualiza();
    }//GEN-LAST:event_bInsereDirActionPerformed

    private void vFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vFilhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vFilhoActionPerformed

    private void bPosOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPosOrdemActionPerformed
        txtPos.setText(arv.exibePosOrdem());
    }//GEN-LAST:event_bPosOrdemActionPerformed

    private void bPreOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPreOrdemActionPerformed
        txtPre.setText(arv.exibePreOrdem());
    }//GEN-LAST:event_bPreOrdemActionPerformed

    private void bInOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInOrdemActionPerformed
        txtIn.setText(arv.exibeInOrdem());
    }//GEN-LAST:event_bInOrdemActionPerformed

    private void bBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscaActionPerformed
        atualiza();
        boolean achou = false;
        int vpai = Integer.parseInt(vBusca.getText());
        int valor;
        
        for(int i = 0; i < 7;i++){
            if(label[i].getText() != "") {
               valor = Integer.parseInt(label[i].getText());
            
                if(vpai == valor){
                    achou = true;
                    label[i].setForeground(Color.green);
                    break;
                }
            }
        }
        if(!achou){
            System.out.println("Valor não existente");
        }
    }//GEN-LAST:event_bBuscaActionPerformed

    private void vPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vPaiActionPerformed

    private void vRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vRaizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vRaizActionPerformed

    private void vBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBusca;
    private javax.swing.JButton bInOrdem;
    private javax.swing.JButton bInsereDir;
    private javax.swing.JButton bInsereEsq;
    private javax.swing.JButton bInsereRaiz;
    private javax.swing.JButton bPosOrdem;
    private javax.swing.JButton bPreOrdem;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel no1;
    private javax.swing.JLabel no2;
    private javax.swing.JLabel no3;
    private javax.swing.JLabel no4;
    private javax.swing.JLabel no5;
    private javax.swing.JLabel no6;
    private javax.swing.JLabel raiz;
    private javax.swing.JLabel seta0;
    private javax.swing.JLabel seta1;
    private javax.swing.JLabel seta2;
    private javax.swing.JLabel seta3;
    private javax.swing.JLabel seta4;
    private javax.swing.JLabel seta5;
    private javax.swing.JLabel txtIn;
    private javax.swing.JLabel txtPos;
    private javax.swing.JLabel txtPre;
    private javax.swing.JTextField vBusca;
    private javax.swing.JTextField vFilho;
    private javax.swing.JTextField vPai;
    private javax.swing.JTextField vRaiz;
    // End of variables declaration//GEN-END:variables
}
